// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sndhdletqhugdcugqwei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuZGhkbGV0cWh1Z2RjdWdxd2VpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMzMwMjUsImV4cCI6MjA3MzgwOTAyNX0.5Duvq-Peq1za_WF7dH3u-q_Luodwk3sVZKgX0z7muXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});